### ISSUE TITLE
Sample app down

### ISSUE THREAD

**Issue by vadi2** [chb/mdht-ccda-webapp#1]
The sample app seems to be down.

**Comment by jmandel** [comment]
Hi @vadi2 . 

Should be back online.  But keep in mind that this project has fallen out of sync with the code that NIST runs to validate C-CDAs. As far as I know, updates aren't being published on a regular basis. I'll ping the MDHT team to ask.

  -Josh

**Comment by jmandel** [comment]
Here's the story:

> The MDHT Team has not made any official releases due to lack of funding for the open source community. Making an official release for them entails approvals from OHT and also IBM and other stakeholders who were funding the community.
> 
> In the meantime, the ONC support team has been creating the necessary builds and providing the necessary support for MU2 validation.
> 
> The list of latest builds can be found at : http://sourceforge.net/projects/oht-modeling/files/Nightly%20Builds/Runtime/
> 
> The Releases used by NIST and SITE are present on SITE at http://sitenv.org/web/sit/ccda-validator
> In the Release information, it tells you which version of MDHT is being used by both the NIST Validator and the SITE Validator. The releases can still be downloaded from OHT but they are just regular builds instead of official OHT releases. They go through the same testing process but not the OHT official governance processes for official releases.

So I've updated this tool and the demo server to use the [current version: 201309181634](http://superb-dca2.dl.sourceforge.net/project/oht-modeling/Nightly%20Builds/Runtime/org.openhealthtools.mdht.uml.cda.runtime.N-N20130918-201309181634.zip)

**Comment by vadi2** [comment]
That's really helpful information. Thanks!

I also tried installing the validator locally on Ubuntu 13.04 with maven2
from the official repositories, but halfway in the install of maven
artifacts, a lot of them started coming up as unavailable and the install
failed. Should I raise another ticket for this?

**Comment by jmandel** [comment]
Please try with Ubuntu 13.04 and mvn3 (which works for me).  (If this works
for you, I'll document that dependency.)

 -J

**Comment by vadi2** [comment]
I'll give it a try when I get back to work in a few days, thanks!

**Comment by vadi2** [comment]
Maven 3 worked, thanks!

**Comment by jmandel** [comment]
Excellent, thanks for the update.  README fixed per the reference above.

**Comment by jmandel** [comment]
Note that performance is also much faster than with the 2012 library versions; after the first document, this service should respond in ~1s rather than ~10s.

**Comment by vadi2** [comment]
Yeah, it does seem to be better in that regard.
